version: "3.5"

services:
  web-unit:
    image: nginx
    container_name: $UNITNAME.uwin
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html/index3.html:/usr/share/nginx/html/index.html

networks:
  default:
    external:
      name: external-example
